name: Client tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Build
        # To generate necessary files
        run: mvn package -DskipTests -Pproduction

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Prepare tests
        # TODO: Find out why the first run is failing
        run: npm test
        continue-on-error: true

      - name: Run tests
        run: npm test
